<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoTyper.Core\AutoTyper.Core.csproj" />
    <ProjectReference Include="..\AutoTyper.Desktop\AutoTyper.Desktop.csproj" />
  </ItemGroup>

</Project>
